[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/xtodo-client/browser"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"
